### PR TITLE
Update for sourcekitten integration specs for Jazzy substructure issue

### PR DESCRIPTION
**Pull request by freak4pc**
Rebuild integration specs per @jpsim's request on https://github.com/realm/jazzy/pull/508#issuecomment-205397812

### CODE REVIEW

**Comment by jpsim** [comment]
Looks like everything was deleted rather than updated based on results from `rake rebuild_integration_fixtures`. Are you sure that command worked?

**Comment by freak4pc** [comment]
I'm not sure what I'm doing wrong... ? 
image

**Comment by segiddins** [comment]
Is it possible the `jazzy` command is just error ing now?

**Comment by freak4pc** [comment]
Probably so @segiddins @jpsim . 
It seems it's trying to build with Swift 2.1.1, where Xcode 7.3 (latest stable) is Swift 2.2. 

Changed the version to 2.2 in config.rb, integration_spec.rb and .travis.yml and.
Rebuilt and ran `bundle exec rake rebuild_integration_fixtures` , it doesn't crash with an error now (the `jazzy` binary) 

Still some deletes but also modified. Does this make more sense? 
image

**Comment by jpsim** [comment]
Looks like a new release of Alamofire is incompatible with the Moya podspec, and maybe a few more broken things... in other words, the specs are broken in `master` even without your changes and will need to be fixed before we can reasonably continue,

**Comment by freak4pc** [comment]
Yikes :(

**Comment by jpsim** [comment]
I've updated the integration specs in #512, hopefully that'll pass CI.

**Comment by johnfairh** [comment]
Closing this, not needed any more.

**Pull request closed without merging**
